FROM python:3.10

RUN useradd -ms /bin /bash Aymeline
USER Aymeline

WORKDIR /home/Aymeline

COPY requirements.txt .

RUN pip install -r requirements.txt && rm requirements.txt

COPY ../../projetMAB1 .

ENTRYPOINT ["nbdev_export"]
ENTRYPOINT ["nbdev_preview"]