# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/projetMAB1',
                'doc_host': 'https://AymelineG.github.io',
                'git_url': 'https://github.com/AymelineG/projetMAB1',
                'lib_path': 'projetMAB1'},
  'syms': {'projetMAB1.core': {'projetMAB1.core.foo': ('core.html#foo', 'projetMAB1/core.py')}}}
