# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/projetMAB1',
                'doc_host': 'https://AymelineG.github.io',
                'git_url': 'https://github.com/AymelineG/projetMAB1',
                'lib_path': 'projetMAB1'},
  'syms': { 'projetMAB1.assembler': {'projetMAB1.assembler.assembly': ('modules/assembler.html#assembly', 'projetMAB1/assembler.py')},
            'projetMAB1.core': {'projetMAB1.core.foo': ('core.html#foo', 'projetMAB1/core.py')},
            'projetMAB1.indexer': { 'projetMAB1.indexer.export_video': ('modules/indexer.html#export_video', 'projetMAB1/indexer.py'),
                                    'projetMAB1.indexer.index': ('modules/indexer.html#index', 'projetMAB1/indexer.py')},
            'projetMAB1.model': { 'projetMAB1.model.Model': ('modules/model.html#model', 'projetMAB1/model.py'),
                                  'projetMAB1.model.Model.__init__': ('modules/model.html#model.__init__', 'projetMAB1/model.py'),
                                  'projetMAB1.model.Model.__new__': ('modules/model.html#model.__new__', 'projetMAB1/model.py'),
                                  'projetMAB1.model.Model.get_image_features': ( 'modules/model.html#model.get_image_features',
                                                                                 'projetMAB1/model.py'),
                                  'projetMAB1.model.Model.query': ('modules/model.html#model.query', 'projetMAB1/model.py')},
            'projetMAB1.storage': { 'projetMAB1.storage.Storage': ('modules/storage.html#storage', 'projetMAB1/storage.py'),
                                    'projetMAB1.storage.Storage.load': ('modules/storage.html#storage.load', 'projetMAB1/storage.py')}}}
