# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/modules/assembler.ipynb.

# %% auto 0
__all__ = ['assembly']

# %% ../nbs/modules/assembler.ipynb 1
import ffmpeg
from os.path import basename, splitext
import datetime as dt


# %% ../nbs/modules/assembler.ipynb 2
def assembly(videos : list[str]):
    in_files = ()
    name_ouput_file = ''
    for video in videos:
        in_files += (ffmpeg.input(video, loglevel='warning', copyts=None),)
        name_ouput_file += splitext(basename(video))[0] + '_'
    time = dt.datetime.now()
    time_format = str(time.year) + '-' + str(time.month) + '-' + str(time.day) + '-' + str(time.hour) + '-' + str(time.minute) + '-' + str(time.second) + '-' + str(time.microsecond)
    out_file = "../../data/runtime/resume/" + name_ouput_file + time_format + '.mp4'
    (
        ffmpeg.concat(*in_files).filter('setpts', expr='PTS-STARTPTS').output(out_file, vsync='2').run()
    )
    return out_file
