# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/modules/storage.ipynb.

# %% auto 0
__all__ = ['Storage']

# %% ../nbs/modules/storage.ipynb 1
import pandas as pd
from pathlib import Path

# %% ../nbs/modules/storage.ipynb 2
class Storage:

    @classmethod
    def load(cls):
        path = Path('../data/runtime/index.pkl')

        if path.exists():
            return pd.read_pickle('../data/runtime/index.pkl')
        
        raise FileNotFoundError("No index.pkl found in runtime folder")
